---
opencv_dependencies:
  - build-essential
  - cmake
  - cmake-qt-gui
  - pkg-config
  - libpng12-0
  - libpng12-dev
  - libpng++-dev
  - libpng3
  - libpnglite-dev
  - zlib1g-dbg
  - zlib1g
  - zlib1g-dev
  - pngtools
  - libtiff5-dev
  - libtiff5
  # - libtiffxx0c2
  - libtiff-tools
  - libjpeg8
  - libjpeg8-dev
  - libjpeg8-dbg
  - libjpeg-progs
  - ffmpeg
  - libavcodec-dev
  - libav-tools
  - unzip
  # - libavcodec53
  # - libavformat53
  - libavformat-dev
  - libgstreamer0.10-0-dbg
  - libgstreamer0.10-0
  - libgstreamer0.10-dev
  - libxine1-ffmpeg
  - libxine-dev
  - libxine1-bin
  - libunicap2
  - libunicap2-dev
  - libdc1394-22-dev
  - libdc1394-22
  - libdc1394-utils
  - swig
  - libv4l-0
  - libv4l-dev
  - python-numpy
  - libpython2.7
  - python-dev
  - python2.7-dev
  - libgtk2.0-dev
  - pkg-config
opencv_src_url: "https://github.com/Itseez/opencv/archive/2.4.13.zip"
opencv_src_file: "~/opencv-2.4.13.zip"
opencv_src_dir: "opencv-2.4.13"
opencv_src_build_dir: "build"
opencv_conf_file: "/etc/ld.so.conf.d/opencv.conf"
opencv_bashrc_file: "/etc/bash.bashrc"
