---
- name: Add to repository for ffmpeg installation
  sudo: yes
  apt_repository: repo='ppa:mc3man/trusty-media'

- name: Install dependencies
  sudo: yes
  apt: "name='{{ item }}' state=installed update_cache=yes"
  with_items: opencv_dependencies

- get_url: "url='{{ opencv_src_url }}' dest='{{ opencv_src_file }}'"
  # -n means don't ask to over-write, just skip
- command: "unzip -n {{ opencv_src_file }}"
- file: "path='{{ opencv_src_dir }}/{{ opencv_src_build_dir }}' state=directory recurse=false"
- command: "cmake -G \"Unix Makefiles\" -D CMAKE_CXX_COMPILER=/usr/bin/g++ CMAKE_C_COMPILER=/usr/bin/gcc -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D BUILD_FAT_JAVA_LIB=ON -D INSTALL_TO_MANGLED_PATHS=ON -D INSTALL_CREATE_DISTRIB=ON -D INSTALL_TESTS=ON -D ENABLE_FAST_MATH=ON -D WITH_IMAGEIO=ON -D BUILD_SHARED_LIBS=OFF -D WITH_GSTREAMER=ON .."
  args:
    chdir: "{{ opencv_src_dir }}/{{ opencv_src_build_dir }}"

- name: make opencv
  command: make
  args:
    chdir: "{{ opencv_src_dir }}/{{ opencv_src_build_dir }}"

- name: make install opencv
  command: "make install"
  sudo: yes
  args:
    chdir: "{{ opencv_src_dir }}/{{ opencv_src_build_dir }}"

# - name: Fix driver issue with symlink
#   file: src="/dev/null" dest="/dev/raw1394" state=link

- name: Move cv2.so file to python environment
  sudo: yes
  copy: src="{{ opencv_src_dir }}/{{ opencv_src_build_dir }}/lib/cv2.so" dest="/usr/lib/python2.7/dist-packages/cv2.so"

- name: Check can import cv2 in python
  shell: python -c "import cv2"
